name: bike-service-hub

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Prepare Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm test
              env:
                  DBUSER: ${{ secrets.DBUSER }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  DBNAME: ${{ secrets.DBNAME }}
                  DBTABLE: ${{ secrets.DBTABLE }}
                  DRIVER: ${{ secrets.DRIVER }}

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push to DockerHub
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: ${{ github.repository }}:ci-${{ github.run_number }},${{ github.repository }}:latest

            - name: Configure SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/ssh_key
                  chmod 600 ~/.ssh/ssh_key
              env:
                  SSH_KEY: ${{ secrets.SSH_KEY }}

            - name: Update Server's Docker Image
              run: |
                  cat ~/.ssh/ssh_key
                  ssh -i ~/.ssh/ssh_key "$SSH_USER@$SSH_HOST" 'cd docker && docker-compose pull && docker-compose up -d --no-deps bike-service-hub'
              env:
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}
