name: bike-service-hub

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Prepare Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm test
              env:
                  DBUSER: ${{ secrets.DBUSER }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  DBNAME: ${{ secrets.DBNAME }}
                  DBTABLE: ${{ secrets.DBTABLE }}
                  DRIVER: ${{ secrets.DRIVER }}

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ vars.GITHUB_REPOSITORY_OWNER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push to DockerHub
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: ${{ vars.GITHUB_REPOSITORY }}:ci-${{ vars.GITHUB_RUN_NUMBER }}
                  secrets: |
                      "DBUSER: ${{ secrets.DBUSER }}"
                      "PASSWORD: ${{ secrets.PASSWORD }}"
                      "DBNAME: ${{ secrets.DBNAME }}"
                      "DBTABLE: ${{ secrets.DBTABLE }}"
                      "DRIVER: ${{ secrets.DRIVER }}"
